# Generated by Django 2.2 on 2021-11-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hiking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hike_Name', models.CharField(max_length=200)),
                ('Hike_Length', models.CharField(max_length=100)),
                ('Hike_TrailType', models.CharField(max_length=100)),
                ('Hike_TimeOfYear', models.CharField(max_length=200)),
                ('Hike_Difficulty', models.CharField(max_length=200)),
                ('Hike_TrailHead', models.CharField(max_length=500)),
                ('Hike_Completed', models.CharField(max_length=25)),
                ('Hike_Notes', models.TextField(max_length=5000)),
                ('Hike_Images', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Time', models.TextField(max_length=100)),
                ('Journal_Entry', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=2000)),
                ('degree', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('university', models.CharField(max_length=200)),
                ('previous_work', models.CharField(max_length=1000)),
                ('skills', models.CharField(max_length=200)),
            ],
        ),
    ]
