# Generated by Django 2.2 on 2021-12-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSuite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='Date_Time',
            field=models.TextField(max_length=200),
        ),
    ]
